### ISSUE TITLE
QueryValidators not being executed?

### ISSUE THREAD

**Issue by PeterKneale** [gothinkster/aspnetcore-realworld-example-app#10]
First up - great project - I really like the way features co-habitate a smaller part of the project than usual - I'm sure it leads to cleaner PR's too.

I cant figure this out though.. There are Fluent Validators applied to queries in a few places.
```csharp
        public class QueryValidator : AbstractValidator<Query>
        {
            public QueryValidator()
            {
                RuleFor(x => x.Username).NotNull().NotEmpty();
            }
        }
```
But the Query classes are instantiated manually in the controllers which I believe means that the validation isn't ever being executed.
```csharp
// eg
        [HttpGet("{username}")]
        public async Task<ProfileEnvelope> Get(string username)
        {
            return await _mediator.Send(new Profiles.Details.Query() { Username = username });
        }
// and
        [HttpGet("{slug}")]
        public async Task<ArticleEnvelope> Get(string slug)
        {
            return await _mediator.Send(new Details.Query(slug));
        }
```

The pattern works well with the commands which are bound as part of MVC's request pipeline and have their validation performed before even entering the action..
```csharp
        public async Task<CommentEnvelope> Create(string slug, [FromBody]Create.Command command)
        {
            command.Slug = slug;
            return await _mediator.Send(command);
        }
```
presumably because of this registration
```csharp
    .AddMvc(opt => ......
      .AddFluentValidation(cfg => { cfg.RegisterValidatorsFromAssemblyContaining<Startup>(); });
```
Am i missing something? Is Mediatr meant to be executing those validators?

**Comment by adamhathcock** [comment]
If this isn't currently executing, I need to take a look.  The MediatR pipeline is meant to be executing those validators.  I'll have to check when I get some free time soon.  I might have broken it during an upgrade.

**Comment by adamhathcock** [comment]
Added a MediatR pipeline validator like I've done on another projects.  Things might get validated twice but that's not horrible.  Works in the integration tests
