### ISSUE TITLE
Lack of comments and information.

### ISSUE THREAD

**Issue by VictorioBerra** [gothinkster/aspnetcore-realworld-example-app#12]
I think that there should be a lot more comments in the code of certain projects. For example, the ASP.NET [Core project just says "We based this on someones project" ](https://github.com/gothinkster/aspnetcore-realworld-example-app/blame/master/readme.md#L31) and then never explains [chunks of code like this.](https://github.com/gothinkster/aspnetcore-realworld-example-app/blob/master/src/Conduit/Infrastructure/GroupByApiRootConvention.cs)

**Comment by adamhathcock** [comment]
You can be more specific?  

Pull requests are welcome.
