### ISSUE TITLE
Error while gettings tags list

### ISSUE THREAD

**Issue by jackjwilliams** [gothinkster/aspnetcore-realworld-example-app#15]
I mentioned this in my PR (https://github.com/gothinkster/aspnetcore-realworld-example-app/pull/14), but after the recent change of ValidationPipelineBehavior, after logging in and viewing the homepage which grabs the Tags List, this error is returned:

Unable to resolve service for type 'FluentValidation.IValidator1[Conduit.Features.Tags.List+Query]' while attempting to activate Conduit.Infrastructure.ValidationPipelineBehavior2[Conduit.Features.Tags.List+Query,Conduit.Features.Tags.TagsEnvelope]'.

**Comment by adamhathcock** [comment]
Sorry.  I should have tested the last thing I merged.
