### ISSUE TITLE
Unit Tests and Business Logic.

### ISSUE THREAD

**Issue by VictorioBerra** [gothinkster/aspnetcore-realworld-example-app#18]
Hello,

I am reading my way through the code and am curious about business logic and unit tests, I see there is an integration test project.

Is business logic supposed to go right in the command handler? Would a larger app separate out the logic from the database code inside the handler?

**Comment by adamhathcock** [comment]
If there was real logic to do then yes they should go into different classes that are injected and tested separately.

I chose not to put real unit tests in and only have a couple example integration tests because there isn't any logic other than how data is queried.
