### ISSUE TITLE
Is it possible that ErrorHandlingMiddleware could expose sensitive information?

### ISSUE THREAD

**Issue by VictorioBerra** [gothinkster/aspnetcore-realworld-example-app#27]
It appears that `exception.Message` is sent back to the user for any Exception. Should this be replaced with a constant message?

**Comment by adamhathcock** [comment]
It could be.  This project is not meant to be an enterprise-ready project.  It's an example of how ASP.NET Core works as a REST API with various features.

Normally, yes you would return and error code back to the client and use that to find the exception in your logging to debug and fix issues.

**Comment by VictorioBerra** [comment]
While that is true, there are multiple examples of where we should be adhering to best practices in these apps.

[From the official start guide and spec:](https://github.com/gothinkster/realworld/tree/master/spec#remember-keep-your-codebases-simple-yet-robust)
> Alternatively, you should never forgo following fundamental best practices for the sake of simplicity, lest we teach that same newbie dev the wrong way of doing things.
