### ISSUE TITLE
What happened to my code here?

### ISSUE THREAD

**Issue by VictorioBerra** [gothinkster/aspnetcore-realworld-example-app#40]
https://github.com/gothinkster/aspnetcore-realworld-example-app/blob/bcb6af2515506dba38e6e17cd93d3e2f3770835b/src/Conduit/Infrastructure/Errors/ErrorHandlingMiddleware.cs#L43

I noticed a bunch of code was changed and my localizer is no longer in use. What happened with the merge here? Where did this all come from?

**Comment by VictorioBerra** [comment]
Looks like this PR clobbered it https://github.com/gothinkster/aspnetcore-realworld-example-app/pull/14

**Comment by adamhathcock** [comment]
Apologies.  Please submit a PR to fix.

**Comment by VictorioBerra** [comment]
Thank you.
