### ISSUE TITLE
Token is missing on page refresh

### ISSUE THREAD

**Issue by hosney** [gothinkster/aspnetcore-realworld-example-app#44]
I'm using this backend together with the vue frontend and upon refreshing the page the token seems to be cleared and the /user endpoint returns a 401. Doesn't seem to happen on https://conduit.productionready.io/api.

**Comment by hosney** [comment]
It seems to work if I switch the api to the conduit url so I suspect the problem might lie on the backend.

**Comment by hosney** [comment]
Might have something to do with CORS. When I refresh the page the browser sends an OPTIONS request to /user which it receives a 204 from the server instead of a 200.

**Comment by hosney** [comment]
The issue is in `Conduit.Features.Users.Details.QueryHandler.Handle`. The token needs to be added to the user object.

e.g.
```
var user = _mapper.Map<Domain.Person, User>(person);
user.Token = await _jwtTokenGenerator.CreateToken(person.Username);
return new UserEnvelope(user);
```

**Comment by adamhathcock** [comment]
Do you mind submitting a pull request?
