### ISSUE TITLE
updating tags for article not working

### ISSUE THREAD

**Issue by lastlink** [gothinkster/aspnetcore-realworld-example-app#50]
Should be able to update tags when an article is updated.

**Comment by dsergiu77** [comment]
Hi all,

I found a solution for this issue and I will create a pull request shortly. I will also add some integration tests for this issue.

**Comment by dsergiu77** [comment]
I submitted a PR for this issue.

**Comment by adamhathcock** [comment]
Fixed with https://github.com/gothinkster/aspnetcore-realworld-example-app/pull/55
