### ISSUE TITLE
Database provider SQlLite hard-coded

### ISSUE THREAD

**Issue by dsergiu77** [gothinkster/aspnetcore-realworld-example-app#56]
Hi,

it would be nice if the database provider / connection string is read from a configuration file and not hard-code to SqlLite (in [Startup](https://github.com/gothinkster/aspnetcore-realworld-example-app/blob/master/src/Conduit/Startup.cs) and [ConduitContext](https://github.com/gothinkster/aspnetcore-realworld-example-app/blob/master/src/Conduit/Infrastructure/ConduitContext.cs)).)
I can imagine that someone would like to use an [InMemoryDatabase](https://docs.microsoft.com/en-us/ef/core/providers/in-memory/) for testing.

Greetings,
Sergiu

**Comment by adamhathcock** [comment]
Using a configuration file like old ASP.NET xml config isn't 12 factor app style.

If you want to change the code to use environment variables to gather that info, then I'd accept the PR :)

**Comment by dsergiu77** [comment]
Cool idea, I will try this and submit a PR.

**Comment by adamhathcock** [comment]
Fixed
