### ISSUE TITLE
Implement one database transaction per HTTP API call

### ISSUE THREAD

**Issue by dsergiu77** [gothinkster/aspnetcore-realworld-example-app#59]
There are cases (like in Create/Edit Article commands that multiple calls to SaveChanges are made inside the command). If the second SaveChanges call fails for some reason, the data saved by the first SaveChanges call does not get rolled back, leading to database inconsistencies.

It would be nice to implement a transaction per HTTP API call (as a filter added to the ASP NET core pipeline).

**Comment by dsergiu77** [comment]
I was thinking to implement this functionality as described [here](https://medium.com/agilix/asp-net-core-one-transaction-per-server-roundtrip-baab72b41e91).

**Comment by adamhathcock** [comment]
I've done something similar before but without EF Core.  It's a good idea.

**Comment by dsergiu77** [comment]
Closed.
