### ISSUE TITLE
.net core 2.0 

### ISSUE THREAD

**Issue by bakbuz** [gothinkster/aspnetcore-realworld-example-app#6]
how to upgrade .net core 2.0 ?

the project is not compiled.

**Comment by adamhathcock** [comment]
I’ll update it today hopefully.

What do you mean it’s not compiled?  This is the source code.

**Comment by bakbuz** [comment]
StartupExtensions.cs

'JwtBearerAppBuilderExtensions.UseJwtBearerAuthentication(IApplicationBuilder, JwtBearerOptions)' is obsolete: 'See https://go.microsoft.com/fwlink/?linkid=845470'

![adsiz](https://user-images.githubusercontent.com/2492378/31069353-cf62831e-a764-11e7-9c77-8dad8a3476c6.png)

**Comment by adamhathcock** [comment]
Yeah ASP.NET Core 2.0 changed a lot of things in auth.  I've already done some work: https://github.com/gothinkster/aspnetcore-realworld-example-app/pull/7

Need to revamp building.

**Comment by bakbuz** [comment]
OK thanks.
