### ISSUE TITLE
Missing app.UseAuthentication()?

### ISSUE THREAD

**Issue by aeslinger0** [gothinkster/aspnetcore-realworld-example-app#64]
I must have done something differently because someone would have raised a concern before this, but I could not get `_httpContextAccessor.HttpContext.User?.Claims?.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier)?.Value;` in `CurrentUserAccessor` to return a value. In fact, User.Claims was always empty.

I fixed the problem by adding `app.UseAuthentication();` above `app.UseMvc();` in `Startup.cs`, but I thought I'd mention this in case I did something wrong. How are others getting the claims to appear without this line?

**Comment by adamhathcock** [comment]
This might have been introduced when I upgraded versions.  Do you mind making a pull request for this issue?

**Comment by adamhathcock** [comment]
Fixed.  Didn't notice as I wasn't using that!
