### ISSUE TITLE
cannot use chinese for the title of article

### ISSUE THREAD

**Issue by mahaoming** [gothinkster/aspnetcore-realworld-example-app#66]
![_20190213145836](https://user-images.githubusercontent.com/31064550/52692904-25629000-2fa0-11e9-989f-ace23c6812cc.png)
try to add a article , but the title of the article is chinese, so it will error, use the demo of the official website,it was normal?

**Comment by adamhathcock** [comment]
I haven't specifically tested non-ASCII characters.  If you could make a pull request with a failing test, I'll look into fixing it.
