### ISSUE TITLE
Default connection string is hard-coded, only SQLite can be used.

### ISSUE THREAD

**Issue by benedict-chan** [gothinkster/aspnetcore-realworld-example-app#68]
If not setting the environment variables, the default connection is hard-coded to SQLite as it prefixed with a ` "Filename="`

`           
 var connectionString = _config.GetValue<string>("ASPNETCORE_Conduit_ConnectionString") ??
                                   $"Filename={DEFAULT_DATABASE_FILE}";
`

Also to make it **consistent**, the default variable should be named "connection string" like the environment variable.

**Comment by adamhathcock** [comment]
Thanks!
