### ISSUE TITLE
No License for Repo

### ISSUE THREAD

**Issue by MorganW09** [gothinkster/aspnetcore-realworld-example-app#75]
Taking a look at your repository it doesn't seem like you have a license. Was that intentional? If not, would you be able to add one?

**Comment by adamhathcock** [comment]
Done with https://github.com/gothinkster/aspnetcore-realworld-example-app/commit/097b288a078537d754644f11d00580a06af67e76

**Comment by MorganW09** [comment]
Thanks @adamhathcock . I'm enjoying reading through this implementation of the Real World App. As someone who hasn't really used MediatR before, it's nice to see how it can be used in an app.
