### ISSUE TITLE
Should .dockerignore include .git folder?

### ISSUE THREAD

**Issue by phillijw** [gothinkster/aspnetcore-realworld-example-app#78]
https://github.com/gothinkster/aspnetcore-realworld-example-app/blob/master/.dockerignore

This file doesn't have the `.git` folder in it but I think you would normally want to ignore that. Is that true?

**Comment by adamhathcock** [comment]
Yeah, it should have it.  I usually copy from gitignore so I forget

**Comment by adamhathcock** [comment]
Fixed
