### ISSUE TITLE
Wrong docker command for 'make run' in documentation node "Docker Build"

### ISSUE THREAD

**Issue by tobiasgranlof** [gothinkster/aspnetcore-realworld-example-app#87]
Found out that documentation is not updated with the corresponding 'Makefile'.
'make run' command does not execute 'docker-compose run' it actually runs 'docker-compose up'

I have created a pull request for this.

**Comment by tobiasgranlof** [comment]
I have created a pull request for this now.

**Comment by adamhathcock** [comment]
Fixed with https://github.com/gothinkster/aspnetcore-realworld-example-app/pull/88
